### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by Sithdown** [sdfgeoff/playcanvas-blender-tools#1]
Hello;

I've been trying to use this exporter from Blender, but I don't know how to.
I tried adding this exporter to the Blender addons folder, but it doesn't show in the addons list.

¿How do I use the exporter? Thanks.

**Comment by Sithdown** [comment]
I've created the pull request #2 that fixed the problem. Maybe it's useful to you.

**Comment by sdfgeoff** [comment]
So before your pull request, it only appeared if you ran the script directly, but did not appear in the addon list.
Thanks for the pull request.

If you want to develop it, and don't want to have to keep disabling-re-enabling the script addon from blender, you can use the python file inside Export.blend which will reload and run it for you.
