### ISSUE TITLE
Folder paths relative to blender install

### ISSUE THREAD

**Issue by Sithdown** [sdfgeoff/playcanvas-blender-tools#3]
I've been able to export the models from Blender, but no material files are generated (just the .json and the .mapping.json).

Playcanvas complains because no materials are found.

**Comment by sdfgeoff** [comment]
It should do. Upon running, it should create a small folder structure with three folders: images, meshes and materials. I've just pushed all my latest changes (it was a commit behind), so have another go at it.
Check the console if you are still having issues.

If you export the model as 'Exporter.json' then you should be able to test it using the (now included) index.html file.

It should export the following material properties:
- Diffuse colour
- Emissive colour
- Specular colour
- Opacity
- Backface Culling
- Images mapped to diffuse
- Images mapped to emissive
- Images mapped to specular

The relevant function is about line 247: export_material(mat, mat_path, img_path):

**Comment by Sithdown** [comment]
I've tried now and the exporter generates the materials. For some reason the folders were created on the directory where Blender is installed. That's the reason I didn't find them earlier.

Thank you.

**Comment by sdfgeoff** [comment]
Hmm. I'll have a look into the filepaths a little more - they should be relative to the export directory.

**Comment by sdfgeoff** [comment]
I redid all the filepath mashing for a much cleaner solution in the recent rewrite.
